### ISSUE TITLE
Batching strategy has 5 times as many incomplete tests as complete tests

### ISSUE THREAD

**Issue by smugleafdev** [MarathonLabs/marathon#500] opened 2021-05-17 18:18 UTC
When running with batching strategy, there are many incomplete tests. In a run with <300 tests, there were >1600 incomplete tests:

```
288 passed, 0 failed, 0 ignored tests
Raw: 288 passed, 3 failed, 0 ignored, 1611 incomplete tests
```

**To Reproduce**
````yaml
batchingStrategy:
  type: "fixed-size"
  size: 10
  durationMillis: 200000
  percentile: 80.0
  timeLimit: "-PT1H"
  lastMileLength: 10
````
My setup is running Android UI Espresso tests on three emulators and running Marathon v0.7.0 from the CLI.

**Expected behavior**
I would expect an amount of incomplete tests to be a fraction of the total tests, and not several times the total amount.

**Additional context**
According to the Allure report, all the incomplete tests are at the end of a batch, and incomplete tests stop happening in the last few batches.

**Comment by Malinskiy** [comment] 2021-05-18 00:33
Hey @smugleafdev 

Incomplete tests are tests that have been triggered on the device, but have not been reported as failed/passed/ignored. Most commonly this indicates a problem with a hanging device that doesn't respond or a test that crashes the device.

Btw, how did you get marathon 0.7.0? Are you running a snapshot from develop? Can you please try the last release version?

**Comment by Malinskiy** [comment] 2021-06-07 12:56
I suspect your batch size might also be more than the default batch timeout of 3 minutes. Consider increasing it:
https://marathonlabs.github.io/marathon/doc/configuration.html#test-batch-timeout

**Comment by smugleafdev** [comment] 2021-06-09 15:21
> Btw, how did you get marathon 0.7.0? Are you running a snapshot from develop? Can you please try the last release version?

Yes, we wanted a couple things that had been merged in. Now on 0.6.2

Tried a batch size of only 5 and 10, and each test takes ~3-10s, so pessimistically they should take under 2 minutes.

Before moving to 0.6.2, the test report showed blocks of green suffixed with a sliver of yellow (the Incomplete tests). As of 0.6.2, I don't see any yellow blocks, but it still reports thousands of incompleted tests. If the report didn't say anything I'd have no idea it was doing this, since it still appears to have no functional repercussions.

**Comment by Malinskiy** [comment] 2021-06-09 15:35
It might be that a device immediately fails the execution of the batch. You can see the list of incomplete tests in the raw.json file for example. Seems like these tests are so short that you can't see them in the timeline at all

**Comment by smugleafdev** [comment] 2021-06-09 16:34
They seem to mostly be duration 0 or 1. So I guess my real question is: Why are there a ton of duration 0 tests while batching strategy is on? They all eventually run normally with their standard duration.

For example, I have one test method that was "ran" 49 times. Not going to count them, but it seems it's about half and half either duration 0 or 1, and then the last one is 7948, a reasonable run time.

**Comment by Malinskiy** [comment] 2021-06-10 00:50
Most of the time this indicates a problem with the Android device. You need to figure out what happens during the batch: what's the last actual test and see how that breaks the whole test batch execution. There might be a native crash of the whole device for example and the runtime just restarts: this will stop the test run and if it happens frequently enough - a lot of tests will be incomplete. But since marathon is expecting device failure - the test run succeeds as long as there is at least one working device. This shouldn't discourage you from investigating the failure reason though.

I can take a look if there is a reproducer code somewhere.

**Comment by smugleafdev** [comment] 2021-09-07 19:02
Update: Now that 0.6.3 is out and incomplete tests fail the test run, I've done some more investigating. It seems that the only thing that causes my incompletes are when a batch includes tests from different test classes. It doesn't matter what activities they start or end on, it doesn't matter how long the tests take. The only thing that seems to make a difference (and does so 100% of the time) is when a batch includes tests from different test classes. I can even cut and paste the tests together to go into one test class and they pass without any incompletes.

And it seems that when I delete all the retry code that has been in my codebase, unused, for many months, the problem goes away. Ta-da!

**Closed as completed** 2021-09-07 19:49 UTC
Labels: bug

**Comment by smugleafdev** [comment] 2023-12-06 20:01
Update years later: I was having a similar issue when changing my target emulators from API 28 to API 33, and it was easily solved by increasing the RAM for the new emulators from the default 1.5gb to 3gb.
