### ISSUE TITLE
Dynamic parameters to marathonfile

### ISSUE THREAD

**Issue by NoNews** [MarathonLabs/marathon#470] opened 2021-03-16 18:01 UTC
Hi, thanks for the library!

Could you please clarify if it's possible to pass dynamic parameters to marathon file config somehow?
For instance, for filteringConfiguration. (For one case I'm going to run all tests, for another - only specific ones)

Or the only way for now it's always generate new marathonfile by custom codegen?

**Comment by Malinskiy** [comment] 2021-03-17 03:07
This was a deliberate decision from the get-go with marathon: all your test runs are represented with a Marathonfile. You can have more than one per repository.
The new configuration #413 might change that since this has been a recurring theme with questions.

Can I ask which parts of the config you want to be specified outside of Marathonfile besides test filtering?

**Comment by NoNews** [comment] 2021-03-17 08:20
Thank you. 

In my case only test filtering + maybe instrumentation arguments

**Comment by Malinskiy** [comment] 2021-03-18 00:06
Awesome, thanks for the feedback! I'll make sure this gets into the new configuration's CLI flags

**Comment by snpefk** [comment] 2021-03-18 07:44
Double test filtering

**Comment by tagantroy** [comment] 2021-05-25 21:03
We have plans for making cli configuration more flexible.
1) My initial idea was to support field overrides, it will make configuration more flexible.
For example override for influx host may look like this:
`-Dconfig.override.analyticsConfiguration.influx.url="http://localhost:8086"`
But I think making test filtering easy to use with this feature is not trivial. 
2) Second idea was about introducing [starlark](https://github.com/bazelbuild/starlark) support as separate tool to make it very flexible(Starlark is a dialect of Python) and you can easily write script to create configuration based on input parameters. Biggest advantages of starlark: Deterministic evaluation and Hermetic execution. 

It would be nice to hear your thoughts on this too :)

**Comment by Malinskiy** [comment] 2021-06-08 08:53
A not so obvious feature is that `Marathonfile` supports env substitutions, e.g.:

```yaml
name: "sample-app tests"
outputDir: "${MARATHON_OUTPUT_DIR}"
isCodeCoverageEnabled: true
```

```bash
$ MARATHON_OUTPUT_DIR="build/reports/marathon-custom" marathon
```

**Comment by abhishekbedi1432** [comment] 2022-08-18 06:05
@Malinskiy  Tried this but failed. 
Command line:
`STRATEGY="device-model" /Users/abhishek.bedi/Downloads/marathon-0.7.3/bin/marathon`

MarathonFile:
`name: "sample-ios-app tests"
outputDir: "derived-data/Marathon"
ignoreFailures: true
testClassRegexes: ["^((?!Abstract).)*Tests$"]
poolingStrategy:
  type: "#{STRATEGY}"
batchingStrategy:
  type: "fixed-size"
  size: 1
debug: true
filteringConfiguration:
  allowlist:
    - type: "fully-qualified-test-name"
      values:
        - "sample-appUITests.StoryboardTests#testButton"
        - "sample-appUITests.StoryboardTests#testLabel"
vendorConfiguration:
  type: "iOS"
  derivedDataDir: "derived-data"
  sourceRoot: "sample-appUITests"
  knownHostsPath: ${HOME}/.ssh/known_hosts
  remoteUsername: ${USER}
  remotePrivateKey: ${HOME}/.ssh/marathon
`
**Output:**

` ~/Downloads/marathon-develop/sample/ios-app  STRATEGY="device-model" /Users/abhishek.bedi/Downloads/marathon-0.7.3/bin/marathon
10:02:18.263 [main] INFO  c.m.marathon.cli.ApplicationView - Starting marathon v0.7.3
10:02:18.383 [main] INFO  c.m.m.e.BugsnagExceptionsReporter - Init BugSnag
10:02:18.383 [main] INFO  c.m.marathon.cli.ApplicationView - Checking Marathonfile config
10:02:19.420 [main] INFO  c.m.m.e.BugsnagExceptionsReporter - Finish BugSnag
10:02:19.420 [main] DEBUG com.bugsnag.Bugsnag - Closing connection to Bugsnag
Exception in thread "main" com.malinskiy.marathon.config.exceptions.ConfigurationException: Error parsing config file /Users/abhishek.bedi/Downloads/marathon-develop/sample/ios-app/Marathonfile
	at com.malinskiy.marathon.config.serialization.ConfigurationFactory.parse(ConfigurationFactory.kt:81)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt:42)
	at com.malinskiy.marathon.cli.ApplicationViewKt$main$1.invoke(ApplicationView.kt:29)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at com.malinskiy.marathon.cli.ApplicationViewKt.main(ApplicationView.kt:27)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id '#{STRATEGY}' as a subtype of `com.malinskiy.marathon.config.strategy.PoolingStrategyConfiguration`: known type ids = [abi, combo, device-model, manufacturer, omni, os-version] (for POJO property 'poolingStrategy')
 at [Source: (StringReader); line: 7, column: 9]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2073)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1564)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:298)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:165)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:125)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:539)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer._deserializeUsingPropertyBased(BuilderBasedDeserializer.java:411)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:219)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
	at com.malinskiy.marathon.config.serialization.ConfigurationFactory.parse(ConfigurationFactory.kt:42)
	... 5 more
10:02:19.423 [Thread-2] DEBUG com.bugsnag.Bugsnag - Closing connection to Bugsnag
`

**Closed as completed** 2022-10-19 10:27 UTC
Labels: dynamic-configuration
