### ISSUE TITLE
Invalid task marathon created by the gradle plugin

### ISSUE THREAD

**Issue by SergKhram** [MarathonLabs/marathon#434] opened 2021-01-20 12:24 UTC
Not all permissions are granted if we use debug\AndroidManifest and gradle (marathon gradle plugin - task marathon)
For example we have <uses-permission android:name="android.permission.CAMERA" /> , but when marathon install the apk on emulator - we don't see this permission in App Info (and as the result we see dialog for allowing on camera activity)

Configuration:
gradle 6.5
com.malinskiy.marathon:marathon-gradle-plugin:0.6.0
task marathon with autoGrantedPermission=true 
debug/AndroidManifest with needed permissions

Expected: all permissions are granted correctly from AndroidManifest with task marathon

device: emulator
os: 10 (Android SDK 29)

**Comment by Malinskiy** [comment] 2021-01-20 12:29
I believe the problem is the existance of this marathon task. It shouldn't even be created in the first place: it is a one to one mapping of app variant + test -> marathon task, e.g. debug androidTest -> marathonDebugAndroidTest.

Possibly we can't access the list of variants anymore because of the dynamic configuration.

**Comment by Malinskiy** [comment] 2021-01-31 05:03
After an investigation, there is nothing wrong with the `marathon` task - it is simply an aggregation of all testing tasks marathon creates.

The underlying problem of permissions was related to clearing the data of the app between batches. I've added a relevant section of the documentation to caution users who apply `pm clear` and `adb -g` at the same time #435

I'm closing this issue since there is nothing to do here. Feel free to reopen if there something else I've missed.

**Closed as completed by Malinskiy** 2021-01-31 05:03 UTC
Labels: bug
