### ISSUE TITLE
Running two instances of marathon for Android

### ISSUE THREAD

**Issue by sparepal** [MarathonLabs/marathon#399] opened 2020-08-20 15:10 UTC
One of the Mac terminal comes to a hang when two instances of marathon have started at the same time(with different include serial regexes).

How do I run two marathon test runs concurrently for different apk’s and different emulators?

Similar issue as the below link
https://github.com/Malinskiy/marathon/issues/387#issue-646479190

**Comment by Malinskiy** [comment] 2020-10-11 04:32
Hey @sparepal. Thanks for reporting this.

Would you be able to include everything that is requested on [the issue template for a bug](https://github.com/Malinskiy/marathon/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)? Especially the logs section.

Thanks

**Comment by sparepal** [comment] 2020-10-13 15:29
Hello Malinskiy, 

I'm afraid it would an issue for me to share the logs. Maybe I can share the yaml. Would that work? 

Best,
Sparepal.

**Comment by Malinskiy** [comment] 2020-10-26 04:15
@sparepal, unfortunately, I won't be able to understand what's happening without the log output. I don't need the test names, so you can mask those out if you need to as well as the device ids if that's a concern.

Please fill out what you can and we'll proceed from there

**Comment by Malinskiy** [comment] 2021-02-03 02:33
Could not reproduce. 
<img width="1282" alt="Screen Shot 2021-02-03 at 13 23 50" src="https://user-images.githubusercontent.com/2089114/106689529-3b057000-6624-11eb-9242-4b138b4bd259.png">

Since there are no logs and no additional information provided, there is little I can do here to help. Closing. Feel free to reopen if you can provide additional data requested.

**Closed as completed by Malinskiy** 2021-02-03 02:33 UTC
Labels: bug
