### ISSUE TITLE
com.malinskiy.marathon.config.exceptions.ConfigurationException: Invalid test 

### ISSUE THREAD

**Issue by sonothar** [MarathonLabs/marathon#716] opened 2022-11-25 08:29 UTC
**Describe the bug**
We just updated out App to SDK Target 33. To run ui tests locally against an Android API Level 33 emulator it was necessary to update to the androidx.test version 1.5.0. But when using that version the marathon test run ends in an endless loop with an initializationError, saying "can't locate test bundle". See stacktrace below
The problem does not appear when I use the androidx.test version 1.4.0. But then I cannot run the tests on an Android API Level 33  Emulator.

**To Reproduce**
Steps to reproduce the behaviour:
1. App Target API Level 33
2. Marathon Verison 0.7.6
3. Android Test dependency 
- androidx.test:core:1.5.0
- androidx.test:rules:1.5.0
- androidx.test:runner:1.5.0

**Expected behavior**
The test run is fully executed.

**Logs and reports**
Here is a stacktrace from the jenkins log. This one keeps repeating until I kill the build:
```
E 20:38:02.799 [main @coroutine#80695] <D.0.0.1:5037:emulator-5572]> Unknown vendor exception caught. Considering this a recoverable error
com.malinskiy.marathon.config.exceptions.ConfigurationException: Invalid test db.vendo.android.vendigator.view.verbindungsdetails.VerbindungsdetailsFreieReiseMerkenTest#initializationError: can't locate test bundle
	at com.malinskiy.marathon.android.AndroidTestBundleIdentifier.identify(AndroidTestBundleIdentifier.kt:15)
	at com.malinskiy.marathon.android.adam.AndroidDeviceTestRunner.execute(AndroidDeviceTestRunner.kt:58)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invokeSuspend(AdamAndroidDevice.kt:372)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invoke(AdamAndroidDevice.kt)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invoke(AdamAndroidDevice.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2.invokeSuspend(AdamAndroidDevice.kt:370)
	at (Coroutine boundary.()
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2.invokeSuspend(AdamAndroidDevice.kt:370)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice.execute(AdamAndroidDevice.kt:374)
	at com.malinskiy.marathon.execution.device.DeviceActor$executeBatch$2.invokeSuspend(DeviceActor.kt:187)
Caused by: com.malinskiy.marathon.config.exceptions.ConfigurationException: Invalid test db.vendo.android.vendigator.view.verbindungsdetails.VerbindungsdetailsFreieReiseMerkenTest#initializationError: can't locate test bundle
	at com.malinskiy.marathon.android.AndroidTestBundleIdentifier.identify(AndroidTestBundleIdentifier.kt:15)
	at com.malinskiy.marathon.android.adam.AndroidDeviceTestRunner.execute(AndroidDeviceTestRunner.kt:58)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invokeSuspend(AdamAndroidDevice.kt:372)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invoke(AdamAndroidDevice.kt)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2$1.invoke(AdamAndroidDevice.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
	at com.malinskiy.marathon.android.adam.AdamAndroidDevice$execute$2.invokeSuspend(AdamAndroidDevice.kt:370)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Devices (please complete the following information):**
 - Device: Emulator Pixel 3
 - OS: API Level 33

**Comment by Malinskiy** [comment] 2022-11-25 08:38
@sonothar I think the error is related to test parsing: are you sure that test `db.vendo.android.vendigator.view.verbindungsdetails.VerbindungsdetailsFreieReiseMerkenTest#initializationError` really exists? When executing tests marathon tries to associate each test to a set of apk files you pass to it. Here the error is somehow you have a test that didn’t come from any apk.

**Comment by sonothar** [comment] 2022-11-25 10:02
How could the test not exist? The test is annotated with @HiltAndroidTest and @RunWith(AndroidJUnit4::class). The test itself did not change during the API update. 
Any idea how to check that?

**Comment by Malinskiy** [comment] 2022-11-25 10:29
You can check this by looking in your codebase in the `db.vendo.android.vendigator.view.verbindungsdetails.VerbindungsdetailsFreieReiseMerkenTest` class and looking for `initializationError` method. 

- If this method **exists** then it's not a problem with test parser
- If it **doesn't exist** then it's a problem with test parser

Updating the build tooling as well as test runtime can have this effect

**Comment by sonothar** [comment] 2022-11-25 12:56
There is no method `initializationError`. 
I tried the current build tools version `33.0.1`. That at least solved the problem locally. But the tests still won't run successfully on the jenkins.
Maybe there is an issue with the test parser.

**Comment by Malinskiy** [comment] 2022-11-25 13:02
A sample project to reproduce your problem will help. Pull out your test case declaration into an empty project and verify that it fails and post here a link to the project.
Which test parser are you using by the way? local or remote?

**Comment by Malinskiy** [comment] 2022-12-08 02:22
@sonothar any update on the sample project?

**Comment by Malinskiy** [comment] 2023-02-01 03:23
I've updated the sample project to 1.5.0 and can't reproduce the problem. Closing the issue since reproducer project has not been provided

**Comment by Malinskiy** [comment] 2023-02-01 08:01
I've managed to reproduce this problem in a multi-module scenario, investigating

**Closed as completed** 2023-02-01 10:22 UTC
Labels: bug
