### ISSUE TITLE
Allure integration and allure-results

### ISSUE THREAD

**Issue by QAutomatron** [MarathonLabs/marathon#356] opened 2020-04-28 15:24 UTC
How does integration with `allure` work? 

I see that an `allure-results` directory is created with reports inside, but they do not include `steps` or links from annotation like `@TmsLink`. Is there any configuration to enable these features or it is planned for development?

**Comment by Malinskiy** [comment] 2020-04-29 05:12
Right now we generate the allure-results on the marathon's side. The annotations are parsed using the dex-test-parser and are populated in the report here https://github.com/Malinskiy/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/report/allure/AllureReporter.kt

`@TestLink` specifically - https://github.com/Malinskiy/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/report/allure/AllureReporter.kt#L103

Are you using the FQDN `io.qameta.allure.TmsLink` for your `@TmsLink`?

**Comment by Malinskiy** [comment] 2020-04-29 05:19
We plan to support the on-device generation of `allure-results`, but this is a work in progress and requires several fixes from allure's side which are currently being worked on. If you would like to test these out - feel free to check the branch https://github.com/Malinskiy/marathon/tree/feature/allure-steps

**Comment by QAutomatron** [comment] 2020-04-29 08:26
Got it, thanks for the quick reply. 

> Are you using the FQDN io.qameta.allure.TmsLink for your @TmsLink?

I used the latest Allure library for Android(which creates reports on the device), version `2.0.3` and the `@TmsLink` annotation from `io.qameta.allure.android.annotations.TmsLink` so maybe this is the issue. Will try to switch to "classic" Allure.

**Comment by QAutomatron** [comment] 2020-05-14 18:52
Using `io.qameta.allure:allure-java-commons` instead of `allure-android` works for links. 

But it would be good to implement the usage of `allure-android` (https://github.com/allure-framework/allure-android) and pulling results from the device.

**Comment by Malinskiy** [comment] 2021-02-03 03:35
This (as in integratino with on-device allure framework) is already possible in 0.6.0 with the allure-kotlin support (allure-android is deprecated). See the docs https://malinskiy.github.io/marathon/ven/android.html#allure-kotlin-support

Closing the issue, feel free to reopen if you have more questions around the integration.

**Closed as completed by Malinskiy** 2021-02-03 03:35 UTC

**Comment by stMayhem** [comment] 2021-04-09 11:03
@Malinskiy Hello. Should marathon 0.6.1, include `steps` in the allure report after enabling `allureConfiguration.enabled = true`? I use Kaspresso+Marathon. Now I get reports like this:

[538aa94b-7b57-4bd1-867d-1efa7ce186a1-result.txt](https://github.com/Malinskiy/marathon/files/6285247/538aa94b-7b57-4bd1-867d-1efa7ce186a1-result.txt) [extension and file paths have been changed]

**Comment by Malinskiy** [comment] 2021-04-09 13:04
@stMayhem Just want to confirm that you're using the file from the device and not marathon's own generated report, this is described in the [docs](https://malinskiy.github.io/marathon/ven/android.html#allure-kotlin-support):

> Enabling this option effectively creates two allure reports for each test run:
>
> one from the point of view of the marathon test runner
> one from the point of view of on-device test execution
>
> All allure output from devices will be collected under $output/allure-device-results folder.

**Comment by stMayhem** [comment] 2021-04-09 15:37
Yes, I’m using alure-device-results

**Comment by Malinskiy** [comment] 2021-04-10 03:57
@stMayhem Is there something wrong during the file transfer from device to running host? If not then it's an issue for allure implementation and should be reported to the maintainer

**Comment by stMayhem** [comment] 2021-04-13 15:36
I think the problem is that I am using **kaspresso** `steps`, with allure `steps` (io.qameta.allure.kotlin.Allure.step) it works fine.
