### ISSUE TITLE
Cannot use relative apks paths as it was in previous versions

### ISSUE THREAD

**Issue by neestell** [MarathonLabs/marathon#592] opened 2021-12-13 08:05 UTC
Paths of applicationApk and testApplicationApk are not relative now.

**To Reproduce**
Steps to reproduce the behaviour:
**It was** possible to run test from the root of the repository with apks paths
**Now I must put** ../../ prefix before every apks in case project has multiple structured configuration files
 applicationApk: "../../../../app/build/outputs/apk/dev/debug/app-dev-debug.apk"
  testApplicationApk: "../../../../app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk"

**Expected behavior**
I can use relative apks paths
 applicationApk: ".app/build/outputs/apk/dev/debug/app-dev-debug.apk"
 testApplicationApk: "app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk"

Maybe I forgot something. Can you please explain to me the issue? Thanks

**Comment by Malinskiy** [comment] 2021-12-13 09:57
Hey @neestell, thanks for submitting the issue. Here is a quote from the docs: 

> When specifying relative host file paths in the configuration they will be resolved relative to the directory of the Marathonfile, e.g. if you have /home/user/app/Marathonfile with baseOutputDir = "./output" then the actual path to the output directory will be /home/user/app/output.

The problem is related to inconsistent test runs: depending on the current work directory the run would previously result in a completely different behavior because the path to files would be relative to the unknown workdir.

With the new changes every relative path is resolved relative to the Marathonfile which has a constant path on a file system.
The issue you’re observing is not related to relative paths since `../../../app./build/etc` is a relative path also. The problem here is that you’re now required to migrated existing setup with a convention to start marathon CLI from a specific directory.

Assuming you start from the same directory as before, you can just move the Marathonfile to this location and use previous relative paths.

Just to reiterate: the reason for this change is to facilitate consistent run behavior regardless of the current workdir. Hope this helps.

**Comment by neestell** [comment] 2021-12-14 15:00
Thank you! This helped

**Comment by tagantroy** [comment] 2022-01-25 21:19
Closing this issue, feel free to reopen if needed.

**Closed as completed by tagantroy** 2022-01-25 21:19 UTC
Labels: bug
