### ISSUE TITLE
ADAM reports empty JUnit reports with a negative test duration

### ISSUE THREAD

**Issue by saim80** [MarathonLabs/marathon#429] opened 2020-12-26 01:46 UTC
**Describe the bug**
Run the test with ADAM. Have some incomplete tests.
Final JUnit reports contain no log or stack trace. It also contains a negative test duration.
The reports are corrected once I stop using ADAM.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Tests.
2. Not sure if related but I had some incomplete tests.
3. See JUnit reports after the test run.

+ I noticed device timed out and retried but I'm not sure if this is related because all test failure logs are gone. Even without any device time out.

```
name: "Mighty CI Run"
outputDir: "./test-result"
poolingStrategy:
- type: "omni"
shardingStrategy:
  type: "parallel"
sortingStrategy:
  type: "no-sorting"
batchingStrategy:
  type: "isolate"
uncompletedTestRetryQuota: 100
testClassRegexes:
  - ".*"
vendorConfiguration:
  type: "Android"
  applicationApk: "app/build/outputs/apk/mightybellStaging/debug/app-mightybellStaging-debug.apk"
  testApplicationApk: "app/build/outputs/apk/androidTest/mightybellStaging/debug/app-mightybellStaging-debug-androidTest.apk"
  applicationPmClear: true
  testApplicationPmClear: true
  screenRecordConfiguration:
    preferableRecorderType: "video"
    videoConfiguration:
      enabled: true
      width: 1080
      height: 1920
      bitrateMbps: 2
      timeLimit: 1200
    screenshotConfiguration:
      enabled: true
      width: 1080
      height: 1920
      delayMs: 1000
```

**Expected behavior**
Proper failure logs.

**Logs and reports**
![Screen Shot 2020-12-25 at 8 37 57 PM](https://user-images.githubusercontent.com/316606/103144118-43e45700-46f2-11eb-897b-3c24979ea540.png)

[archive(1).zip](https://github.com/Malinskiy/marathon/files/5742577/archive.1.zip)

**Devices (please complete the following information):**
 - Device: Pixel2 Emulator
 - OS: Android API 26

**Additional context**
N/A

**Comment by Malinskiy** [comment] 2020-12-26 02:44
Hey @saim80, thank you for submitting this.

This is indeed a bug with the incomplete tests. We set up the start time of the test and if the test completes - then we set up the end time as well. Unfortunately, for adam the test run failed doesn't propagate the test run end time. Hence the `0-startTime` being negative.

This is addressed in the https://github.com/Malinskiy/marathon/commit/f0cb83605c43393615fe1af7aabee5d48464c751 by setting up the end time.

Please try using the latest CLI snapshot and verify if the negative duration is fixed for your use-case. The PR for this fix is pending full code review #426 

As for the stacktrace - there is no stacktrace for this test since it has not finished execution. The real problem is #428 which I'll address in the next release. For now you can remove the test retry quota completely and the test should be marked as failed after doing all of the retries. Please report in the #428 if that's not the case.

**Comment by saim80** [comment] 2020-12-26 16:25
@Malinskiy I found a build error after merging the PR commit. I fixed locally to move on. Just FYI, 
![Screen Shot 2020-12-26 at 11 22 55 AM](https://user-images.githubusercontent.com/316606/103155338-ee995b80-476c-11eb-9838-59684f387107.png)

**Comment by saim80** [comment] 2020-12-26 18:04
@Malinskiy I confirmed the fix. However, I'm encountering this error when I use ADAM. 
![Screen Shot 2020-12-26 at 12 38 07 PM](https://user-images.githubusercontent.com/316606/103156793-86ea0d00-477a-11eb-82f5-b2d83de215ca.png)

When I switch back to ddmlib, I get this error.
![Screen Shot 2020-12-26 at 1 03 26 PM](https://user-images.githubusercontent.com/316606/103156817-d0d2f300-477a-11eb-9df3-350bf138eb9e.png)

I cannot tell whether they are the same or not. From the stacktrace, they seem to be different types of timeouts.

**Comment by saim80** [comment] 2020-12-26 18:15
Maybe, the above errors aren't really relevant to this thread. I can create another thread for this.

**Comment by saim80** [comment] 2020-12-27 01:48
Oh, the screen capturer timeout probably was from the PR changes I merged. You are introducing timeout config under Android section. I guess increasing the timeout will probably fix my issue above.

**Comment by saim80** [comment] 2020-12-27 01:49
Running 9 emulators on a single made me to increase timeouts to allow the test possible but overall it was totally worthwhile.

**Comment by Malinskiy** [comment] 2020-12-27 01:55
Unfortunately increasing timeouts most likely will not change anything. The new timeouts are much more granular compared to ddmlib.
The source of the timeouts is adb server and adbd implementation on the device which are out of our control.
Both errors you see have the same root cause: socket times out. You don't have to worry about it in this case: you might miss a frame in the gif.

**Comment by saim80** [comment] 2020-12-27 02:01
@Malinskiy I see. Thanks for the explanation!

**Closed as completed** 2020-12-27 02:00 UTC
Labels: bug
