### ISSUE TITLE
Provide a way to run Android tests against specific emulators

### ISSUE THREAD

**Issue by tabletenniser** [MarathonLabs/marathon#804] opened 2023-06-08 19:56 UTC
In our CI / CD environment, we have a pool of 10 emulators: emu-1, emu-2, ... emu-10. But for a particular run, we only want to use 2 of them (e.g emu-3, emu-4) since there are other concurrent runs happening at the same time using other emulators. Is it possible to add a configuration so that we can provide `-s` flag to the underlying `adb shell am instrument` command?  Some configuration in the YAML file like `emulatorToUse` will be very helpful! Example config I would image:
```
name: ...
outputDir: ...
vendorConfiguration:
  type: "Android"
  emulatorsToUse: "emu-3, emu-4"
```

Looking at the https://docs.marathonlabs.io/ I don't see any configuration on that.

**Comment by tabletenniser** [comment] 2023-06-08 22:49
Um, actually, after a closer look at the Marathon code, the `includeSerialRegexes` field may be exactly what I want: https://github.com/MarathonLabs/marathon/blob/8e3a40e9dfeb8b5eed8d70b61762e1c6e8ebf575/core/src/main/kotlin/com/malinskiy/marathon/execution/Scheduler.kt#L131  Is there any reason why that field isn't documented in https://docs.marathonlabs.io/ ?

**Comment by Malinskiy** [comment] 2023-06-09 01:04
Hey @tabletenniser, thanks for submitting the issue.

This seems to be a duplicate of https://github.com/MarathonLabs/marathon/issues/387

Filtering by device serial is undocumented for a reason: it's a bad idea unless you really know what you are doing.

When sharing devices across multiple runs you're prone to such issues as:
1. Adb server shared between runs means a crash in one run will crash all the runs
2. Mistakes in specifying devices will slip through and using same device in different test runs in marathon is undefined behaviour
3. When specifying devices that are missing during runtime your test run will fail with no devices available. You should treat your devices as ephemeral and not depend on any specifics of compute, just like you don't care which server runs your container in kubernetes

If all of the above are okay for your use-case then feel free to go with the parameters mentioned above in the issue.

**Comment by Malinskiy** [comment] 2023-06-10 04:55
@tabletenniser please let me know if you need more information otherwise you can close the issue.
Thanks :)

**Comment by tabletenniser** [comment] 2023-06-10 06:01
> @tabletenniser please let me know if you need more information otherwise you can close the issue.
> Thanks :)

Yup, thanks for the reply and detailed info. We can close this.

**Closed as completed** 2023-06-10 06:03 UTC
Labels: enhancement
